[package]
name = "r2ce"
version = "0.1.0"
authors = ["ozgend"]
edition = "2018"

[dependencies]
serde_json = "1.0.64"
minreq = "2.3.1"
embedded-websocket = "0.5.0"
futures = "0.3.13"
tokio = { version = "1.4.0", features = ["full"] }
rand  = "0.8.3"