[package]
name = "r2ce"
version = "0.1.0"
authors = ["ozgend"]
edition = "2018"

[dependencies]
serde_json = "1.0.64"
minreq = "2.3.1"
rust_socketio = "0.2.0"
tokio = { version = "1.4.0", features = ["full"] }
event-bus = "0.1.0"
