[package]
name = "r2ce"
version = "0.1.0"
authors = ["ozgend"]
edition = "2018"

[dependencies]
futures = "0.3.13"
serde_json = "1.0.64"
reqwest = { version = "0.11.2", features= ["gzip", "json"]}
tokio = { version = "1.4.0", features = ["full"] }
rust_socketio = "0.2.0"